import type { Metadata } from "next";
import { Geist } from "next/font/google";

import "@repo/ui/styles.css";
import "@repo/shadcn/styles/globals.css";
import "./globals.css";

import ThemeWatcher from "#/provider/theme-providers";
import { getLocale, getMessages } from "next-intl/server";
import { NextIntlClientProvider } from "next-intl";

import RefreshBrowserProvider from "#/provider/refresh-browser-providers";

import { Toaster } from "@repo/shadcn/components/ui/sonner";

const geist = Geist({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const locale = await getLocale();
  const messages = await getMessages();
  return (
    <html lang={locale} suppressHydrationWarning>
      <body className={geist.className}>
        <Toaster />
        <RefreshBrowserProvider>
          <NextIntlClientProvider messages={messages}>
            <ThemeWatcher>{children}</ThemeWatcher>
          </NextIntlClientProvider>
        </RefreshBrowserProvider>
      </body>
    </html>
  );
}
