import "@repo/ui/styles.css";
import "@repo/shadcn/styles/globals.css";
import "./globals.css";
import type { Metadata } from "next";
import { Geist } from "next/font/google";

import { ThemeProvider } from "next-themes";

const geist = Geist({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="zh" suppressHydrationWarning>
      <body className={geist.className}>
        {" "}
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          {children}{" "}
        </ThemeProvider>
      </body>
    </html>
  );
}
